/**
 * monday-adapter.ts — Multi-tenant Monday.com data layer.
 *
 * Supports two tenants, each with its own API key env var:
 *   - `xome`        → process.env.MONDAY_XOME_API_KEY        (Xome Mortgage Team account)
 *   - `culbertson`  → process.env.MONDAY_CULBERTSON_API_KEY  (C&G account — legacy)
 *
 * Consumers call `getMondayData(widgetKey)` and receive:
 *   - on success:  `{ data: <transformed>, error: null }`
 *   - on missing key or any fetch error: `{ data: null, error: <message> }`
 *
 * Widgets treat `data: null` as the ComingSoon state and never crash server
 * components.
 *
 * All board/column/group/status mappings are pulled from the inventory
 * generated by `docs/xome-monday-inventory.json` during Phase 1 discovery.
 * Re-run `/tmp/xome-build-inventory.py` to regenerate.
 */

// ─── Types ──────────────────────────────────────────────────────────────

export type Tenant = 'xome' | 'culbertson'

export type WidgetKey =
  | 'xome.loan_pipeline'
  | 'xome.loan_officer_roster'
  | 'xome.loan_volume_kpis'
  | 'xome.compliance'
  | 'xome.warehouse_reconciliation'
  | 'xome.power'
  | 'xome.recent_closed_loans'
  | 'culbertson.loan_pipeline'            // legacy — not yet wired
  | 'culbertson.sales_volume_ytd'         // C&C Monday — Sales Volume YTD/MTD
  | 'culbertson.sales_volume_mtd'         // (alias — same board, MTD slice)
  | 'culbertson.gci_ytd'                  // Estimated gross commission income
  | 'culbertson.gci_mtd'                  // GCI MTD slice
  | 'culbertson.closed_transactions'      // Closed transaction count by period
  | 'culbertson.avg_commission_pct'       // Average commission % (proxy)
  | 'culbertson.top_producers'            // Agent leaderboard by closed volume
  | 'culbertson.pipeline_value'           // Total $ in active deals
  | 'culbertson.revenue_by_source'        // Self-gen vs team-gen vs referral
  | 'culbertson.monthly_revenue'          // 12-month trend
  | 'culbertson.expense_categories'       // Company Expenses breakdown
  | 'culbertson.ad_spend_by_agent'        // Agent Ad Spend board (not yet wired)

export interface BoardMapping {
  tenant: Tenant
  widgetKey: WidgetKey
  boardId: string
  columns: Record<string, string>  // friendly -> monday column id
  groupMap?: Record<string, string>
  statusMap?: Record<string, string>
  transform?: (items: MondayItem[], mapping: BoardMapping) => unknown
}

export interface MondayItem {
  id: string
  name: string
  group?: { id: string; title: string }
  column_values: Array<{ id: string; type: string; text: string | null; value: string | null }>
}

export interface MondayResult<T = unknown> {
  data: T | null
  error: string | null
  cached?: boolean
}

// ─── Tenant → env var ────────────────────────────────────────────────────

const ENV_KEY_BY_TENANT: Record<Tenant, string> = {
  xome: 'MONDAY_XOME_API_KEY',
  culbertson: 'MONDAY_CULBERTSON_API_KEY',
}

function apiKeyForTenant(tenant: Tenant): string | null {
  const envVar = ENV_KEY_BY_TENANT[tenant]
  const v = process.env[envVar]
  return v && v.trim() ? v.trim() : null
}

// ─── In-memory cache (60s TTL) ──────────────────────────────────────────

interface CacheEntry {
  data: unknown
  expiresAt: number
}

const CACHE = new Map<string, CacheEntry>()
const CACHE_TTL_MS = 60_000

function cacheGet(key: string): unknown | null {
  const e = CACHE.get(key)
  if (!e) return null
  if (Date.now() > e.expiresAt) {
    CACHE.delete(key)
    return null
  }
  return e.data
}

function cacheSet(key: string, data: unknown): void {
  CACHE.set(key, { data, expiresAt: Date.now() + CACHE_TTL_MS })
}

// ─── GraphQL fetch ──────────────────────────────────────────────────────

export async function mondayFetch<T = unknown>(
  tenant: Tenant,
  query: string,
  variables: Record<string, unknown> = {}
): Promise<MondayResult<T>> {
  const apiKey = apiKeyForTenant(tenant)
  if (!apiKey) {
    return { data: null, error: `${ENV_KEY_BY_TENANT[tenant]} not configured` }
  }

  try {
    const res = await fetch('https://api.monday.com/v2', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: apiKey,
        'API-Version': '2024-01',
      },
      body: JSON.stringify({ query, variables }),
      cache: 'no-store',
    })

    if (res.status === 401) {
      return { data: null, error: '401 Unauthorized — bad or expired Monday token' }
    }
    if (res.status === 429) {
      return { data: null, error: '429 Rate limited by Monday API — try again in 60s' }
    }
    if (!res.ok) {
      return { data: null, error: `Monday API HTTP ${res.status}` }
    }

    const json = (await res.json()) as { data?: T; errors?: unknown[] }
    if (json.errors?.length) {
      return { data: null, error: `Monday API errors: ${JSON.stringify(json.errors)}` }
    }
    return { data: (json.data as T) ?? null, error: null }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    return { data: null, error: msg }
  }
}

// ─── Board mappings (from docs/xome-monday-inventory.json) ──────────────

const XOME_LOAN_PIPELINE_BOARD = '5842083369'

export const BOARD_MAPPINGS: BoardMapping[] = [
  // Loan Pipeline — primary production board (928 items, 7 groups)
  {
    tenant: 'xome',
    widgetKey: 'xome.loan_pipeline',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      last_name: 'name',
      first_name: 'text_1',
      lo: 'people',
      loa: 'people0',
      processor: 'people_2',
      stage: 'status',
      lender: 'label__1',
      lead_source: 'status_18',
      loan_purpose: 'dup__of_loan_purpose',
      loan_type: 'status_14',
      property_state: 'status106',
      property_address: 'location',
      estimated_value: 'numbers_1',
      est_loan_amount: 'numbers89',
      le_loan_amount: 'numbers4',
      appraised_value: 'numbers5',
      fico: 'numbers59',
      created_at: 'creation_log',
      updated_at: 'last_updated',
      pre_approved: 'date_1',
      coe: 'date_9',
      ctc: 'date6',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
    groupMap: {
      topics: 'Leads',
      new_group23653: 'Pre-Approved',
      new_group41491: 'In Process',
      group_mks3286t: 'New Group',
      new_group62657: 'Funded',
      new_group13782: 'Nurture',
      new_group9764: 'Dead/DNC',
    },
    statusMap: {
      '0': 'Registered',
      '1': 'Funded',
      '2': 'Incoming Registration',
      '3': 'Incoming Lead',
      '4': 'Contact Attempted Lead',
      '6': 'Contacted Lead',
      '9': 'CTC',
      '10': 'Appraisal Completed',
      '12': 'Loan Approved',
      '13': 'Loan Submitted',
      '18': 'Pre-Approved',
      '19': 'Appraisal Ordered',
      '105': 'Nurture',
      '106': 'Dead/Do Not Contact',
    },
  },

  // Loan Officer Roster — derived from the same Loan Pipeline board
  {
    tenant: 'xome',
    widgetKey: 'xome.loan_officer_roster',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      lo: 'people',
      stage: 'status',
      est_loan_amount: 'numbers89',
      le_loan_amount: 'numbers4',
      coe: 'date_9',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
  },

  // Loan Volume KPIs — derived from same board
  {
    tenant: 'xome',
    widgetKey: 'xome.loan_volume_kpis',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      stage: 'status',
      est_loan_amount: 'numbers89',
      le_loan_amount: 'numbers4',
      created_at: 'creation_log',
      coe: 'date_9',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
  },

  // Recent closed loans — same board, filtered to funded
  {
    tenant: 'xome',
    widgetKey: 'xome.recent_closed_loans',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      last_name: 'name',
      first_name: 'text_1',
      stage: 'status',
      lo: 'people',
      le_loan_amount: 'numbers4',
      est_loan_amount: 'numbers89',
      property_state: 'status106',
      loan_type: 'status_14',
      loan_purpose: 'dup__of_loan_purpose',
      coe: 'date_9',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
  },

  // Compliance Tracker — 0 items at discovery, column schema preserved
  {
    tenant: 'xome',
    widgetKey: 'xome.compliance',
    boardId: '18140546461',
    columns: {
      invoice_status: 'status4__1',
      processor_compliance: 'status_16',
      date_received: 'date4',
      cleared: 'status0',
      loan_amount_mirror: 'mirror',
      lo_mirror: 'mirror5',
    },
    groupMap: {
      new_group85895: 'Pending Compliance',
      new_group: 'Compliance Completed',
    },
  },

  // Warehouse Reconciliation — 0 items at discovery
  {
    tenant: 'xome',
    widgetKey: 'xome.warehouse_reconciliation',
    boardId: '18140546824',
    columns: {
      loan_amount_mirror: 'mirror3',
      warehouse_mirror: 'mirror4',
      lo_mirror: 'mirror0',
      funded_date_mirror: 'mirror6',
      total_wire: 'numbers980',
      to_be_funded: 'formula1',
      haircut: 'formula6',
      amount_due_investor: 'numbers96',
    },
    groupMap: {
      topics: 'Not Reconciled Yet',
      group_title: 'Reconciled',
    },
  },

  // Xome Power — solar board, small (3 items at discovery)
  {
    tenant: 'xome',
    widgetKey: 'xome.power',
    boardId: '6386432034',
    columns: {
      name: 'name',
      stage: 'status0',
      contacted: 'status9',
      street_address: 'text',
      city: 'text_1',
      financier: 'status68',
      installer: 'status72',
      date: 'date4',
    },
    groupMap: {
      topics: 'Incoming Leads',
      new_group52585: 'Proposal',
      new_group22586: 'Project',
      new_group22822: 'Completed',
      new_group: 'Nurture',
      new_group45402: 'Dead',
    },
  },

  // ─── Culbertson & Gray (C&G) ─────────────────────────────────────────────
  // Closed Sales (4119151716) — 2269 items, grouped by calendar month
  //   "April 2026", "March 2026", … "January 2023". One group per month.
  //   Columns: name (property addr), text4 (Agent), numbers (Price),
  //   numbers9 (Individual Agent Totals = sale price), dropdown__1 (Source),
  //   dropdown5__1 (Lender). No raw commission $ — GCI computed as
  //   estimate (2.5% of sale price, industry-typical company-side split).
  //
  // Transactions in Process (1404826328) — 610 items, pipeline groups
  //   + real Company Revenue column.
  //   Groups: new_group68267 (New Form Submissions), duplicate_of_active_listings__1
  //   (Pre-Listed/Held), new_group7848 (Active Listings), topics (Current Pendings),
  //   new_group (Closed), new_group76088 (Cancelled).
  //   Columns: numbers3__1 (Price), numeric (Company Revenue), coe_date_ (COE Date),
  //   agent1 (Agent), lead_source2 (Lead Source), buyer_seller, closed_escrow,
  //   splits_added_ (text like "80/20"), status (Splits Added to Skyslope).
  //
  // Company Expenses (8737854919) — 32 items grouped by office location.
  //   Columns: status (Region), color_mkp64tx7 (Frequency), numeric_mkp6z60y
  //   (Amount), text_mkp6edy6 (Point of Contact), text_mkp6cjwz (Company Name),
  //   text_mkp7fkd4 (Payment Type).
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.sales_volume_ytd',
    boardId: '4119151716',
    columns: {
      agent: 'text4',
      sale_price: 'numbers',
      individual_total: 'numbers9',
      source: 'dropdown__1',
      lender: 'dropdown5__1',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.sales_volume_mtd',
    boardId: '4119151716',
    columns: {
      agent: 'text4',
      sale_price: 'numbers',
      individual_total: 'numbers9',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.gci_ytd',
    boardId: '4119151716',
    columns: {
      agent: 'text4',
      sale_price: 'numbers',
      individual_total: 'numbers9',
      source: 'dropdown__1',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.gci_mtd',
    boardId: '4119151716',
    columns: {
      agent: 'text4',
      sale_price: 'numbers',
      individual_total: 'numbers9',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.closed_transactions',
    boardId: '4119151716',
    columns: {
      agent: 'text4',
      sale_price: 'numbers',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.avg_commission_pct',
    boardId: '1404826328',
    columns: {
      sale_price: 'numbers3__1',
      company_revenue: 'numeric',
      splits_text: 'splits_added_',
      coe_date: 'coe_date_',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.top_producers',
    boardId: '4119151716',
    columns: {
      agent: 'text4',
      sale_price: 'numbers',
      individual_total: 'numbers9',
      source: 'dropdown__1',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.pipeline_value',
    boardId: '1404826328',
    columns: {
      sale_price: 'numbers3__1',
      company_revenue: 'numeric',
      agent: 'agent1',
      coe_date: 'coe_date_',
      buyer_seller: 'buyer_seller',
      property_status: 'closed_escrow',
      lead_source: 'lead_source2',
    },
    groupMap: {
      new_group68267: 'New Form Submissions',
      duplicate_of_active_listings__1: 'Pre-Listed/Held',
      new_group7848: 'Active Listings',
      topics: 'Current Pendings',
      new_group: 'Closed',
      new_group76088: 'Cancelled',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.revenue_by_source',
    boardId: '4119151716',
    columns: {
      agent: 'text4',
      sale_price: 'numbers',
      individual_total: 'numbers9',
      source: 'dropdown__1',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.monthly_revenue',
    boardId: '4119151716',
    columns: {
      sale_price: 'numbers',
      individual_total: 'numbers9',
      agent: 'text4',
      source: 'dropdown__1',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.expense_categories',
    boardId: '8737854919',
    columns: {
      region: 'status',
      frequency: 'color_mkp64tx7',
      amount: 'numeric_mkp6z60y',
      payment_type: 'text_mkp7fkd4',
      auto_payment: 'color_mkp7k3yg',
      company: 'text_mkp6cjwz',
    },
    groupMap: {
      group_title: 'General Applications',
      topics: 'Roseville Office',
      group_mkp8zmfr: 'Lincoln Office',
      group_mkp8x93t: 'Reno Office',
      group_mkpbvdy4: 'South Lake Tahoe Office',
    },
  },
  // Agent Ad Spend workspace (10192135) has no populated board at discovery
  // time — only a "Start from scratch" board with 10 generic test rows.
  // Mapping is a placeholder that returns an empty ad-spend view; widget
  // will degrade gracefully.
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.ad_spend_by_agent',
    boardId: '8650358630',
    columns: {
      agent: 'person',
      stage: 'status',
      date: 'date4',
    },
  },
]

const MAPPING_BY_KEY: Record<string, BoardMapping> = Object.fromEntries(
  BOARD_MAPPINGS.map(m => [m.widgetKey, m])
)

// ─── Redaction helpers (for borrower display) ──────────────────────────

export function redactName(lastName: string | null, firstName?: string | null): string {
  const last = (lastName || '').trim()
  const first = (firstName || '').trim()
  if (first && last) return `${first[0]?.toUpperCase() ?? ''}. ${last}`
  if (last) return last
  if (first) return `${first[0]?.toUpperCase() ?? ''}.`
  return '—'
}

function parseNum(text: string | null | undefined): number {
  if (!text) return 0
  const n = Number(String(text).replace(/[^0-9.-]/g, ''))
  return Number.isFinite(n) ? n : 0
}

function cvText(item: MondayItem, id: string | undefined): string {
  if (!id) return ''
  const cv = item.column_values.find(c => c.id === id)
  return cv?.text ?? ''
}

// ─── Board fetchers ─────────────────────────────────────────────────────

/**
 * Paginate through all items on a board using cursor-based items_page.
 * Returns a flat array of items with the specified column_values.
 */
async function fetchBoardItems(
  tenant: Tenant,
  boardId: string,
  columnIds: string[],
  pageSize = 200
): Promise<MondayResult<MondayItem[]>> {
  const firstQuery = `
    query ($boardId: ID!, $columnIds: [String!], $limit: Int!) {
      boards(ids: [$boardId]) {
        items_page(limit: $limit) {
          cursor
          items {
            id
            name
            group { id title }
            column_values(ids: $columnIds) { id type text value }
          }
        }
      }
    }
  `
  const nextQuery = `
    query ($cursor: String!, $columnIds: [String!], $limit: Int!) {
      next_items_page(cursor: $cursor, limit: $limit) {
        cursor
        items {
          id
          name
          group { id title }
          column_values(ids: $columnIds) { id type text value }
        }
      }
    }
  `

  const r = await mondayFetch<{
    boards: Array<{ items_page: { cursor: string | null; items: MondayItem[] } }>
  }>(tenant, firstQuery, { boardId, columnIds, limit: pageSize })

  if (r.error || !r.data) return { data: null, error: r.error ?? 'No data' }

  const collected: MondayItem[] = []
  let cursor = r.data.boards?.[0]?.items_page?.cursor ?? null
  collected.push(...(r.data.boards?.[0]?.items_page?.items ?? []))

  // Safety cap to avoid infinite loops (board has 928 items; cap at ~5k)
  let hops = 0
  while (cursor && hops < 25) {
    hops++
    const n = await mondayFetch<{
      next_items_page: { cursor: string | null; items: MondayItem[] }
    }>(tenant, nextQuery, { cursor, columnIds, limit: pageSize })
    if (n.error || !n.data) break
    collected.push(...(n.data.next_items_page?.items ?? []))
    cursor = n.data.next_items_page?.cursor ?? null
  }

  return { data: collected, error: null }
}

// ─── Widget transforms ──────────────────────────────────────────────────

interface LoanPipelineStage {
  group_id: string
  group_name: string
  count: number
  total_amount: number
}

interface LoanPipelineView {
  board_id: string
  total_items: number
  total_active_amount: number
  stages: LoanPipelineStage[]
  generated_at: string
}

function transformLoanPipeline(items: MondayItem[], m: BoardMapping): LoanPipelineView {
  const groupMap = m.groupMap ?? {}
  const stages: Record<string, LoanPipelineStage> = {}

  // Seed every group so empty stages still render
  for (const [gid, gname] of Object.entries(groupMap)) {
    stages[gid] = { group_id: gid, group_name: gname, count: 0, total_amount: 0 }
  }

  for (const it of items) {
    const gid = it.group?.id ?? 'unknown'
    const gname = groupMap[gid] ?? it.group?.title ?? 'Other'
    if (!stages[gid]) stages[gid] = { group_id: gid, group_name: gname, count: 0, total_amount: 0 }
    stages[gid].count++

    // Prefer LE loan amount → estimated loan amount → estimated value
    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount)) ||
      parseNum(cvText(it, m.columns.estimated_value))
    stages[gid].total_amount += amount
  }

  // Keep the groups in the same declaration order as groupMap; unknowns last
  const ordered: LoanPipelineStage[] = []
  const seen = new Set<string>()
  for (const gid of Object.keys(groupMap)) {
    if (stages[gid]) {
      ordered.push(stages[gid])
      seen.add(gid)
    }
  }
  for (const [gid, s] of Object.entries(stages)) {
    if (!seen.has(gid)) ordered.push(s)
  }

  const active_groups = new Set(['topics', 'new_group23653', 'new_group41491', 'group_mks3286t'])
  const total_active_amount = ordered
    .filter(s => active_groups.has(s.group_id))
    .reduce((sum, s) => sum + s.total_amount, 0)

  return {
    board_id: m.boardId,
    total_items: items.length,
    total_active_amount,
    stages: ordered,
    generated_at: new Date().toISOString(),
  }
}

interface LoanOfficerRow {
  name: string
  loan_count: number
  active_count: number
  funded_count: number
  volume_mtd: number
  volume_ytd: number
}

function transformLoanOfficers(items: MondayItem[], m: BoardMapping): LoanOfficerRow[] {
  const now = new Date()
  const mtdStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const ytdStart = new Date(now.getFullYear(), 0, 1)

  const officers = new Map<string, LoanOfficerRow>()

  for (const it of items) {
    const loText = cvText(it, m.columns.lo)
    const loName = loText?.trim() || 'Unassigned'
    if (!officers.has(loName)) {
      officers.set(loName, {
        name: loName,
        loan_count: 0,
        active_count: 0,
        funded_count: 0,
        volume_mtd: 0,
        volume_ytd: 0,
      })
    }
    const rec = officers.get(loName)!
    rec.loan_count++

    const stage = cvText(it, m.columns.stage) || ''
    const groupId = it.group?.id ?? ''
    const isFunded = stage === 'Funded' || groupId === 'new_group62657'
    const isDead = groupId === 'new_group9764' || groupId === 'new_group13782'

    if (isFunded) rec.funded_count++
    else if (!isDead) rec.active_count++

    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount))
    const closeStr = cvText(it, m.columns.coe) || cvText(it, m.columns.wire_disbursement)

    if (isFunded && amount > 0 && closeStr) {
      const closeDate = new Date(closeStr)
      if (!isNaN(closeDate.getTime())) {
        if (closeDate >= ytdStart) rec.volume_ytd += amount
        if (closeDate >= mtdStart) rec.volume_mtd += amount
      }
    }
  }

  return Array.from(officers.values())
    .filter(r => r.name !== 'Unassigned')
    .sort((a, b) => b.volume_ytd - a.volume_ytd || b.funded_count - a.funded_count)
}

interface LoanVolumeKPIs {
  volume_mtd: number
  volume_ytd: number
  loans_funded_mtd: number
  loans_funded_ytd: number
  avg_loan_size: number
  pipeline_value: number
  pipeline_count: number
  avg_days_to_close: number | null
  pull_through_rate: number | null
}

function transformLoanVolumeKPIs(items: MondayItem[], m: BoardMapping): LoanVolumeKPIs {
  const now = new Date()
  const mtdStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const ytdStart = new Date(now.getFullYear(), 0, 1)

  let volume_mtd = 0
  let volume_ytd = 0
  let loans_funded_mtd = 0
  let loans_funded_ytd = 0
  let funded_sum = 0
  let funded_count = 0
  let pipeline_value = 0
  let pipeline_count = 0
  const closeDays: number[] = []

  const active_groups = new Set(['topics', 'new_group23653', 'new_group41491', 'group_mks3286t'])

  for (const it of items) {
    const stage = cvText(it, m.columns.stage) || ''
    const groupId = it.group?.id ?? ''
    const isFunded = stage === 'Funded' || groupId === 'new_group62657'

    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount))

    if (isFunded && amount > 0) {
      const closeStr = cvText(it, m.columns.coe) || cvText(it, m.columns.wire_disbursement)
      const closeDate = closeStr ? new Date(closeStr) : null
      const createdStr = cvText(it, m.columns.created_at)
      const createdDate = createdStr ? new Date(createdStr) : null

      funded_sum += amount
      funded_count++

      if (closeDate && !isNaN(closeDate.getTime())) {
        if (closeDate >= ytdStart) {
          volume_ytd += amount
          loans_funded_ytd++
        }
        if (closeDate >= mtdStart) {
          volume_mtd += amount
          loans_funded_mtd++
        }
        if (createdDate && !isNaN(createdDate.getTime())) {
          const days = Math.round((closeDate.getTime() - createdDate.getTime()) / 86_400_000)
          if (days > 0 && days < 365) closeDays.push(days)
        }
      }
    }

    if (active_groups.has(groupId)) {
      pipeline_count++
      pipeline_value += amount
    }
  }

  const avg_days_to_close =
    closeDays.length > 0 ? Math.round(closeDays.reduce((a, b) => a + b, 0) / closeDays.length) : null
  const avg_loan_size = funded_count > 0 ? funded_sum / funded_count : 0
  const totalCountable = items.filter(it => {
    const gid = it.group?.id ?? ''
    return gid !== 'new_group9764' && gid !== 'new_group13782'
  }).length
  const pull_through_rate = totalCountable > 0 ? funded_count / totalCountable : null

  return {
    volume_mtd,
    volume_ytd,
    loans_funded_mtd,
    loans_funded_ytd,
    avg_loan_size,
    pipeline_value,
    pipeline_count,
    avg_days_to_close,
    pull_through_rate,
  }
}

interface ClosedLoanRow {
  id: string
  borrower: string
  amount: number
  lo: string
  state: string
  loan_type: string
  loan_purpose: string
  close_date: string | null
}

function transformRecentClosed(items: MondayItem[], m: BoardMapping, limit = 10): ClosedLoanRow[] {
  const rows: ClosedLoanRow[] = []
  for (const it of items) {
    const stage = cvText(it, m.columns.stage) || ''
    const groupId = it.group?.id ?? ''
    const isFunded = stage === 'Funded' || groupId === 'new_group62657'
    if (!isFunded) continue

    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount))
    const closeStr = cvText(it, m.columns.coe) || cvText(it, m.columns.wire_disbursement) || null

    rows.push({
      id: it.id,
      borrower: redactName(it.name, cvText(it, m.columns.first_name)),
      amount,
      lo: cvText(it, m.columns.lo) || '—',
      state: cvText(it, m.columns.property_state) || '—',
      loan_type: cvText(it, m.columns.loan_type) || '—',
      loan_purpose: cvText(it, m.columns.loan_purpose) || '—',
      close_date: closeStr,
    })
  }
  rows.sort((a, b) => {
    const ad = a.close_date ? new Date(a.close_date).getTime() : 0
    const bd = b.close_date ? new Date(b.close_date).getTime() : 0
    return bd - ad
  })
  return rows.slice(0, limit)
}

interface ComplianceView {
  board_id: string
  total_items: number
  pending_count: number
  completed_count: number
  overdue_count: number
  items: Array<{
    id: string
    name: string
    group: string
    date_received: string | null
    processor_compliance: string
    invoice_status: string
    cleared: string
    overdue: boolean
  }>
}

function transformCompliance(items: MondayItem[], m: BoardMapping): ComplianceView {
  const now = Date.now()
  const overdueWindowMs = 14 * 86_400_000

  const rows = items.map(it => {
    const dateStr = cvText(it, m.columns.date_received)
    const date = dateStr ? new Date(dateStr) : null
    const overdue =
      !!date && !isNaN(date.getTime()) && now - date.getTime() > overdueWindowMs &&
      !cvText(it, m.columns.cleared).toLowerCase().includes('yes')
    const gid = it.group?.id ?? ''
    const gname = m.groupMap?.[gid] ?? it.group?.title ?? 'Other'
    return {
      id: it.id,
      name: it.name,
      group: gname,
      date_received: dateStr || null,
      processor_compliance: cvText(it, m.columns.processor_compliance),
      invoice_status: cvText(it, m.columns.invoice_status),
      cleared: cvText(it, m.columns.cleared),
      overdue,
    }
  })

  const pending_count = rows.filter(r => r.group === 'Pending Compliance').length
  const completed_count = rows.filter(r => r.group === 'Compliance Completed').length
  const overdue_count = rows.filter(r => r.overdue).length

  return {
    board_id: m.boardId,
    total_items: items.length,
    pending_count,
    completed_count,
    overdue_count,
    items: rows.slice(0, 20),
  }
}

interface WarehouseView {
  board_id: string
  open_count: number
  reconciled_count: number
  total_pending_value: number
  total_haircut: number
  oldest_open_days: number | null
}

function transformWarehouse(items: MondayItem[], m: BoardMapping): WarehouseView {
  let open_count = 0
  let reconciled_count = 0
  let total_pending_value = 0
  let total_haircut = 0
  let oldest_ms: number | null = null
  const now = Date.now()

  for (const it of items) {
    const gid = it.group?.id ?? ''
    const amount = parseNum(cvText(it, m.columns.total_wire)) || parseNum(cvText(it, m.columns.loan_amount_mirror))
    const haircut = parseNum(cvText(it, m.columns.haircut))

    if (gid === 'topics') {
      open_count++
      total_pending_value += amount
      total_haircut += haircut
      const fundedStr = cvText(it, m.columns.funded_date_mirror)
      if (fundedStr) {
        const d = new Date(fundedStr).getTime()
        if (!isNaN(d) && (oldest_ms === null || d < oldest_ms)) oldest_ms = d
      }
    } else if (gid === 'group_title') {
      reconciled_count++
    }
  }

  const oldest_open_days =
    oldest_ms !== null ? Math.floor((now - oldest_ms) / 86_400_000) : null

  return {
    board_id: m.boardId,
    open_count,
    reconciled_count,
    total_pending_value,
    total_haircut,
    oldest_open_days,
  }
}

interface XomePowerView {
  board_id: string
  total_items: number
  stages: Array<{ group_id: string; group_name: string; count: number }>
  items: Array<{ id: string; name: string; group: string; stage: string; contacted: string; city: string }>
}

function transformXomePower(items: MondayItem[], m: BoardMapping): XomePowerView {
  const groupMap = m.groupMap ?? {}
  const stages: Record<string, { group_id: string; group_name: string; count: number }> = {}
  for (const [gid, gname] of Object.entries(groupMap)) {
    stages[gid] = { group_id: gid, group_name: gname, count: 0 }
  }
  for (const it of items) {
    const gid = it.group?.id ?? 'unknown'
    if (!stages[gid]) {
      stages[gid] = { group_id: gid, group_name: it.group?.title ?? 'Other', count: 0 }
    }
    stages[gid].count++
  }
  return {
    board_id: m.boardId,
    total_items: items.length,
    stages: Object.values(stages),
    items: items.slice(0, 10).map(it => {
      const lastName = (it.name || '').split(' ')[0] || '—'
      return {
        id: it.id,
        name: `${lastName[0]?.toUpperCase() || ''}. ${it.name?.split(' ').slice(1).join(' ') || ''}`.trim() || it.name,
        group: m.groupMap?.[it.group?.id ?? ''] ?? it.group?.title ?? 'Other',
        stage: cvText(it, m.columns.stage),
        contacted: cvText(it, m.columns.contacted),
        city: cvText(it, m.columns.city),
      }
    }),
  }
}

// ─── Culbertson transforms ──────────────────────────────────────────────

/**
 * Closed Sales (4119151716) uses calendar-month group titles ("April 2026",
 * "March 2026", …). Parse each group's title into a (year, month) pair so we
 * can filter by YTD / MTD / last-N-months without relying on a date column.
 */
function parseClosedSalesGroup(title: string): { year: number; month: number } | null {
  if (!title) return null
  const m = /^\s*([A-Za-z]+)\s+(\d{4})\s*$/.exec(title)
  if (!m) return null
  const monthNames = [
    'january', 'february', 'march', 'april', 'may', 'june',
    'july', 'august', 'september', 'october', 'november', 'december',
  ]
  const mm = monthNames.indexOf(m[1].toLowerCase())
  if (mm < 0) return null
  return { year: Number(m[2]), month: mm }
}

/**
 * Industry-standard assumption: company GCI is ~2.5% of sale price. Closed
 * Sales does not carry a raw commission column, so GCI is an ESTIMATE based
 * on this rate. Company Revenue (post-split) on Transactions in Process is
 * a separate number — we surface both where available.
 */
const GCI_ESTIMATE_RATE = 0.025

interface VolumeKPI {
  ytd: number
  mtd: number
  prev_month: number
  last_12m: number
  all_time: number
  count_ytd: number
  count_mtd: number
  avg_price_ytd: number
}

function transformCulbertsonVolume(items: MondayItem[], m: BoardMapping): VolumeKPI {
  const now = new Date()
  const yr = now.getFullYear()
  const mo = now.getMonth()
  const prevYr = mo === 0 ? yr - 1 : yr
  const prevMo = mo === 0 ? 11 : mo - 1

  const priceCol = m.columns.individual_total || m.columns.sale_price

  let ytd = 0, mtd = 0, prev_month = 0, last_12m = 0, all_time = 0
  let count_ytd = 0, count_mtd = 0

  for (const it of items) {
    const price = parseNum(cvText(it, priceCol))
    if (price <= 0) continue
    all_time += price

    const g = parseClosedSalesGroup(it.group?.title ?? '')
    if (!g) continue

    if (g.year === yr) {
      ytd += price
      count_ytd++
      if (g.month === mo) {
        mtd += price
        count_mtd++
      }
    }
    if (g.year === prevYr && g.month === prevMo) {
      prev_month += price
    }
    // Last 12 months (rolling, inclusive of current month)
    const monthsAgo = (yr - g.year) * 12 + (mo - g.month)
    if (monthsAgo >= 0 && monthsAgo < 12) last_12m += price
  }

  return {
    ytd,
    mtd,
    prev_month,
    last_12m,
    all_time,
    count_ytd,
    count_mtd,
    avg_price_ytd: count_ytd > 0 ? Math.round(ytd / count_ytd) : 0,
  }
}

interface GciKPI {
  gci_ytd: number
  gci_mtd: number
  gci_prev_month: number
  gci_last_12m: number
  rate: number          // 0.025
  volume_ytd: number    // underlying sales volume for context
  volume_mtd: number
}

function transformCulbertsonGci(items: MondayItem[], m: BoardMapping): GciKPI {
  const vol = transformCulbertsonVolume(items, m)
  return {
    gci_ytd: Math.round(vol.ytd * GCI_ESTIMATE_RATE),
    gci_mtd: Math.round(vol.mtd * GCI_ESTIMATE_RATE),
    gci_prev_month: Math.round(vol.prev_month * GCI_ESTIMATE_RATE),
    gci_last_12m: Math.round(vol.last_12m * GCI_ESTIMATE_RATE),
    rate: GCI_ESTIMATE_RATE,
    volume_ytd: vol.ytd,
    volume_mtd: vol.mtd,
  }
}

interface ClosedTxKPI {
  ytd: number
  mtd: number
  prev_month: number
  last_12m: number
  all_time: number
  by_month: Array<{ month_key: string; label: string; count: number }>
}

function transformCulbertsonClosedCount(items: MondayItem[], m: BoardMapping): ClosedTxKPI {
  const now = new Date()
  const yr = now.getFullYear()
  const mo = now.getMonth()
  const prevYr = mo === 0 ? yr - 1 : yr
  const prevMo = mo === 0 ? 11 : mo - 1

  let ytd = 0, mtd = 0, prev_month = 0, last_12m = 0, all_time = 0
  const counts = new Map<string, { label: string; count: number }>()

  for (const it of items) {
    const price = parseNum(cvText(it, m.columns.sale_price))
    if (price <= 0) continue
    all_time++

    const g = parseClosedSalesGroup(it.group?.title ?? '')
    if (!g) continue

    const key = `${g.year}-${String(g.month + 1).padStart(2, '0')}`
    const label = it.group?.title ?? key
    const entry = counts.get(key) ?? { label, count: 0 }
    entry.count++
    counts.set(key, entry)

    if (g.year === yr) {
      ytd++
      if (g.month === mo) mtd++
    }
    if (g.year === prevYr && g.month === prevMo) prev_month++
    const monthsAgo = (yr - g.year) * 12 + (mo - g.month)
    if (monthsAgo >= 0 && monthsAgo < 12) last_12m++
  }

  const by_month = Array.from(counts.entries())
    .sort(([a], [b]) => (a < b ? 1 : a > b ? -1 : 0))
    .slice(0, 24)
    .map(([k, v]) => ({ month_key: k, label: v.label, count: v.count }))

  return { ytd, mtd, prev_month, last_12m, all_time, by_month }
}

/** Parse "80/20", "65/35 35% Zillow", etc. → company split percentage (20, 35). */
function parseSplitText(s: string | null): number | null {
  if (!s) return null
  const m = /(\d+)\s*\/\s*(\d+)/.exec(s)
  if (!m) return null
  const a = Number(m[1]), b = Number(m[2])
  if (!Number.isFinite(a) || !Number.isFinite(b) || a + b === 0) return null
  // Heuristic: the smaller of the two numbers is the company %
  return Math.min(a, b)
}

interface AvgCommissionKPI {
  avg_company_split_pct: number   // mean of smaller side of "80/20" style
  median_company_split_pct: number
  implied_company_rate_pct: number // company_revenue / sale_price × 100 (median of populated rows)
  n: number
  note: string
}

function transformCulbertsonAvgCommission(items: MondayItem[], m: BoardMapping): AvgCommissionKPI {
  const splits: number[] = []
  const rates: number[] = []
  for (const it of items) {
    const txt = cvText(it, m.columns.splits_text)
    const split = parseSplitText(txt)
    if (split !== null) splits.push(split)

    const price = parseNum(cvText(it, m.columns.sale_price))
    const rev = parseNum(cvText(it, m.columns.company_revenue))
    if (price > 1000 && rev > 0) {
      rates.push((rev / price) * 100)
    }
  }

  const median = (xs: number[]): number => {
    if (!xs.length) return 0
    const sorted = [...xs].sort((a, b) => a - b)
    const mid = Math.floor(sorted.length / 2)
    return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2
  }
  const mean = (xs: number[]): number => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0)

  return {
    avg_company_split_pct: Math.round(mean(splits) * 10) / 10,
    median_company_split_pct: Math.round(median(splits) * 10) / 10,
    implied_company_rate_pct: Math.round(median(rates) * 100) / 100,
    n: splits.length,
    note: 'Company side of the split parsed from "XX/YY" text. Implied rate from Company Revenue ÷ Price.',
  }
}

interface TopProducerRow {
  agent: string
  count_ytd: number
  volume_ytd: number
  volume_all: number
  est_gci_ytd: number
}

function transformCulbertsonTopProducers(items: MondayItem[], m: BoardMapping): TopProducerRow[] {
  const now = new Date()
  const yr = now.getFullYear()
  const priceCol = m.columns.individual_total || m.columns.sale_price

  const agents = new Map<string, TopProducerRow>()
  for (const it of items) {
    const agent = (cvText(it, m.columns.agent) || '').trim()
    if (!agent || agent.toLowerCase() === 'unassigned') continue
    const price = parseNum(cvText(it, priceCol))
    if (price <= 0) continue

    const row = agents.get(agent) ?? {
      agent,
      count_ytd: 0,
      volume_ytd: 0,
      volume_all: 0,
      est_gci_ytd: 0,
    }
    row.volume_all += price

    const g = parseClosedSalesGroup(it.group?.title ?? '')
    if (g && g.year === yr) {
      row.count_ytd++
      row.volume_ytd += price
    }
    agents.set(agent, row)
  }

  for (const row of agents.values()) {
    row.est_gci_ytd = Math.round(row.volume_ytd * GCI_ESTIMATE_RATE)
  }

  return Array.from(agents.values())
    .sort((a, b) => b.volume_ytd - a.volume_ytd || b.volume_all - a.volume_all)
    .slice(0, 25)
}

interface RevenueBySourceRow {
  source: string
  count_ytd: number
  volume_ytd: number
  est_gci_ytd: number
  pct_of_ytd: number
}

interface RevenueBySourceView {
  total_ytd: number
  est_total_gci_ytd: number
  sources: RevenueBySourceRow[]
}

function transformCulbertsonRevenueBySource(items: MondayItem[], m: BoardMapping): RevenueBySourceView {
  const now = new Date()
  const yr = now.getFullYear()
  const priceCol = m.columns.individual_total || m.columns.sale_price

  const sources = new Map<string, RevenueBySourceRow>()
  let total_ytd = 0

  for (const it of items) {
    const g = parseClosedSalesGroup(it.group?.title ?? '')
    if (!g || g.year !== yr) continue
    const price = parseNum(cvText(it, priceCol))
    if (price <= 0) continue
    const src = (cvText(it, m.columns.source) || 'Unspecified').trim() || 'Unspecified'

    const row = sources.get(src) ?? {
      source: src,
      count_ytd: 0,
      volume_ytd: 0,
      est_gci_ytd: 0,
      pct_of_ytd: 0,
    }
    row.count_ytd++
    row.volume_ytd += price
    sources.set(src, row)
    total_ytd += price
  }

  const out = Array.from(sources.values())
  for (const r of out) {
    r.est_gci_ytd = Math.round(r.volume_ytd * GCI_ESTIMATE_RATE)
    r.pct_of_ytd = total_ytd > 0 ? Math.round((r.volume_ytd / total_ytd) * 1000) / 10 : 0
  }
  out.sort((a, b) => b.volume_ytd - a.volume_ytd)

  return {
    total_ytd,
    est_total_gci_ytd: Math.round(total_ytd * GCI_ESTIMATE_RATE),
    sources: out,
  }
}

interface MonthlyRevenuePoint {
  month_key: string      // "2026-04"
  label: string          // "Apr 2026"
  year: number
  month: number          // 0-11
  volume: number
  est_gci: number
  deal_count: number
}

interface MonthlyRevenueView {
  points: MonthlyRevenuePoint[]   // most recent 12 months, oldest-first
  total_volume: number
  total_est_gci: number
  peak_month: MonthlyRevenuePoint | null
  current_month: MonthlyRevenuePoint | null
}

function transformCulbertsonMonthlyRevenue(items: MondayItem[], m: BoardMapping): MonthlyRevenueView {
  const priceCol = m.columns.individual_total || m.columns.sale_price
  const now = new Date()
  const currYr = now.getFullYear()
  const currMo = now.getMonth()

  // Build all 12 month slots (oldest → newest)
  const slots: MonthlyRevenuePoint[] = []
  for (let i = 11; i >= 0; i--) {
    const d = new Date(currYr, currMo - i, 1)
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
    const label = d.toLocaleDateString('en-US', { month: 'short', year: 'numeric' })
    slots.push({
      month_key: key,
      label,
      year: d.getFullYear(),
      month: d.getMonth(),
      volume: 0,
      est_gci: 0,
      deal_count: 0,
    })
  }
  const idx = new Map<string, MonthlyRevenuePoint>()
  for (const s of slots) idx.set(s.month_key, s)

  for (const it of items) {
    const g = parseClosedSalesGroup(it.group?.title ?? '')
    if (!g) continue
    const key = `${g.year}-${String(g.month + 1).padStart(2, '0')}`
    const point = idx.get(key)
    if (!point) continue

    const price = parseNum(cvText(it, priceCol))
    if (price <= 0) continue
    point.volume += price
    point.deal_count++
  }

  let peak: MonthlyRevenuePoint | null = null
  let total_volume = 0
  for (const s of slots) {
    s.est_gci = Math.round(s.volume * GCI_ESTIMATE_RATE)
    total_volume += s.volume
    if (!peak || s.volume > peak.volume) peak = s
  }

  return {
    points: slots,
    total_volume,
    total_est_gci: Math.round(total_volume * GCI_ESTIMATE_RATE),
    peak_month: peak,
    current_month: slots[slots.length - 1] ?? null,
  }
}

interface PipelineStage {
  group_id: string
  group_name: string
  count: number
  volume: number
  company_revenue: number
}

interface PipelineView {
  board_id: string
  total_items: number
  active_count: number
  active_volume: number
  active_company_revenue: number
  pending_count: number
  pending_volume: number
  stages: PipelineStage[]
}

function transformCulbertsonPipeline(items: MondayItem[], m: BoardMapping): PipelineView {
  const groupMap = m.groupMap ?? {}
  const stages: Record<string, PipelineStage> = {}
  for (const [gid, gname] of Object.entries(groupMap)) {
    stages[gid] = { group_id: gid, group_name: gname, count: 0, volume: 0, company_revenue: 0 }
  }

  for (const it of items) {
    const gid = it.group?.id ?? 'unknown'
    const gname = groupMap[gid] ?? it.group?.title ?? 'Other'
    if (!stages[gid]) stages[gid] = { group_id: gid, group_name: gname, count: 0, volume: 0, company_revenue: 0 }
    const s = stages[gid]
    s.count++
    s.volume += parseNum(cvText(it, m.columns.sale_price))
    s.company_revenue += parseNum(cvText(it, m.columns.company_revenue))
  }

  const activeIds = new Set([
    'new_group68267', 'duplicate_of_active_listings__1', 'new_group7848', 'topics',
  ])
  const pendingIds = new Set(['topics'])

  let active_count = 0, active_volume = 0, active_company_revenue = 0
  let pending_count = 0, pending_volume = 0
  for (const s of Object.values(stages)) {
    if (activeIds.has(s.group_id)) {
      active_count += s.count
      active_volume += s.volume
      active_company_revenue += s.company_revenue
    }
    if (pendingIds.has(s.group_id)) {
      pending_count += s.count
      pending_volume += s.volume
    }
  }

  // Preserve declaration order
  const ordered: PipelineStage[] = []
  const seen = new Set<string>()
  for (const gid of Object.keys(groupMap)) {
    if (stages[gid]) { ordered.push(stages[gid]); seen.add(gid) }
  }
  for (const [gid, s] of Object.entries(stages)) {
    if (!seen.has(gid)) ordered.push(s)
  }

  return {
    board_id: m.boardId,
    total_items: items.length,
    active_count,
    active_volume,
    active_company_revenue,
    pending_count,
    pending_volume,
    stages: ordered,
  }
}

interface ExpenseRow {
  id: string
  name: string
  company: string
  region: string
  frequency: string
  amount: number
  monthly_equiv: number
  payment_type: string
  auto_payment: string
  office: string
}

interface ExpenseView {
  board_id: string
  total_items: number
  total_annual: number
  total_monthly_equiv: number
  by_office: Array<{ office: string; count: number; annual: number; monthly: number }>
  by_frequency: Array<{ frequency: string; count: number; annual: number }>
  rows: ExpenseRow[]
}

function freqToMonthlyMultiplier(freq: string): number {
  const f = (freq || '').toLowerCase()
  if (f.includes('year') || f.includes('annual')) return 1 / 12
  if (f.includes('quarter')) return 1 / 3
  if (f.includes('month')) return 1
  if (f.includes('week')) return 52 / 12
  if (f.includes('one') || f.includes('once')) return 0
  return 1 // default to monthly when unknown to avoid hiding costs
}

function freqToAnnualMultiplier(freq: string): number {
  const f = (freq || '').toLowerCase()
  if (f.includes('year') || f.includes('annual')) return 1
  if (f.includes('quarter')) return 4
  if (f.includes('month')) return 12
  if (f.includes('week')) return 52
  if (f.includes('one') || f.includes('once')) return 1
  return 12
}

function transformCulbertsonExpenses(items: MondayItem[], m: BoardMapping): ExpenseView {
  const rows: ExpenseRow[] = items.map(it => {
    const freq = cvText(it, m.columns.frequency) || 'Unknown'
    const amount = parseNum(cvText(it, m.columns.amount))
    const office = m.groupMap?.[it.group?.id ?? ''] ?? it.group?.title ?? 'Other'
    return {
      id: it.id,
      name: it.name,
      company: cvText(it, m.columns.company) || it.name,
      region: cvText(it, m.columns.region),
      frequency: freq,
      amount,
      monthly_equiv: amount * freqToMonthlyMultiplier(freq),
      payment_type: cvText(it, m.columns.payment_type),
      auto_payment: cvText(it, m.columns.auto_payment),
      office,
    }
  })

  const byOffice = new Map<string, { office: string; count: number; annual: number; monthly: number }>()
  const byFreq = new Map<string, { frequency: string; count: number; annual: number }>()
  let total_annual = 0
  let total_monthly = 0

  for (const r of rows) {
    const annual = r.amount * freqToAnnualMultiplier(r.frequency)
    total_annual += annual
    total_monthly += r.monthly_equiv

    const oe = byOffice.get(r.office) ?? { office: r.office, count: 0, annual: 0, monthly: 0 }
    oe.count++
    oe.annual += annual
    oe.monthly += r.monthly_equiv
    byOffice.set(r.office, oe)

    const fe = byFreq.get(r.frequency) ?? { frequency: r.frequency, count: 0, annual: 0 }
    fe.count++
    fe.annual += annual
    byFreq.set(r.frequency, fe)
  }

  return {
    board_id: m.boardId,
    total_items: rows.length,
    total_annual: Math.round(total_annual),
    total_monthly_equiv: Math.round(total_monthly),
    by_office: Array.from(byOffice.values()).sort((a, b) => b.annual - a.annual),
    by_frequency: Array.from(byFreq.values()).sort((a, b) => b.annual - a.annual),
    rows: rows.sort((a, b) => b.amount - a.amount),
  }
}

// ─── Public API ─────────────────────────────────────────────────────────

export async function getMondayData(widgetKey: WidgetKey): Promise<MondayResult> {
  const mapping = MAPPING_BY_KEY[widgetKey]
  if (!mapping) {
    return { data: null, error: `Unknown widget key: ${widgetKey}` }
  }

  const cacheKey = `${mapping.tenant}:${widgetKey}`
  const cached = cacheGet(cacheKey)
  if (cached) {
    return { data: cached, error: null, cached: true }
  }

  // If no API key, short-circuit with explicit error
  if (!apiKeyForTenant(mapping.tenant)) {
    return { data: null, error: `${ENV_KEY_BY_TENANT[mapping.tenant]} not configured` }
  }

  // Collect column IDs we need + always include `name`, `group`
  const columnIds = Array.from(new Set(Object.values(mapping.columns))).filter(Boolean)
  const result = await fetchBoardItems(mapping.tenant, mapping.boardId, columnIds)
  if (result.error || !result.data) {
    return { data: null, error: result.error ?? 'No items returned' }
  }

  let transformed: unknown
  try {
    switch (widgetKey) {
      case 'xome.loan_pipeline':
        transformed = transformLoanPipeline(result.data, mapping)
        break
      case 'xome.loan_officer_roster':
        transformed = transformLoanOfficers(result.data, mapping)
        break
      case 'xome.loan_volume_kpis':
        transformed = transformLoanVolumeKPIs(result.data, mapping)
        break
      case 'xome.recent_closed_loans':
        transformed = transformRecentClosed(result.data, mapping)
        break
      case 'xome.compliance':
        transformed = transformCompliance(result.data, mapping)
        break
      case 'xome.warehouse_reconciliation':
        transformed = transformWarehouse(result.data, mapping)
        break
      case 'xome.power':
        transformed = transformXomePower(result.data, mapping)
        break
      // ─── Culbertson ──────────────────────────────────────────────────
      case 'culbertson.sales_volume_ytd':
      case 'culbertson.sales_volume_mtd':
        transformed = transformCulbertsonVolume(result.data, mapping)
        break
      case 'culbertson.gci_ytd':
      case 'culbertson.gci_mtd':
        transformed = transformCulbertsonGci(result.data, mapping)
        break
      case 'culbertson.closed_transactions':
        transformed = transformCulbertsonClosedCount(result.data, mapping)
        break
      case 'culbertson.avg_commission_pct':
        transformed = transformCulbertsonAvgCommission(result.data, mapping)
        break
      case 'culbertson.top_producers':
        transformed = transformCulbertsonTopProducers(result.data, mapping)
        break
      case 'culbertson.pipeline_value':
        transformed = transformCulbertsonPipeline(result.data, mapping)
        break
      case 'culbertson.revenue_by_source':
        transformed = transformCulbertsonRevenueBySource(result.data, mapping)
        break
      case 'culbertson.monthly_revenue':
        transformed = transformCulbertsonMonthlyRevenue(result.data, mapping)
        break
      case 'culbertson.expense_categories':
        transformed = transformCulbertsonExpenses(result.data, mapping)
        break
      default:
        transformed = result.data
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    return { data: null, error: `Transform failed: ${msg}` }
  }

  cacheSet(cacheKey, transformed)
  return { data: transformed, error: null }
}

// Helpful re-exports for widget code
export type {
  LoanPipelineView,
  LoanPipelineStage,
  LoanOfficerRow,
  LoanVolumeKPIs,
  ClosedLoanRow,
  ComplianceView,
  WarehouseView,
  XomePowerView,
  VolumeKPI,
  GciKPI,
  ClosedTxKPI,
  AvgCommissionKPI,
  TopProducerRow,
  RevenueBySourceRow,
  RevenueBySourceView,
  MonthlyRevenuePoint,
  MonthlyRevenueView,
  PipelineStage,
  PipelineView as CulbertsonPipelineView,
  ExpenseRow,
  ExpenseView,
}
