/**
 * monday-adapter.ts — Multi-tenant Monday.com data layer.
 *
 * Supports two tenants, each with its own API key env var:
 *   - `xome`        → process.env.MONDAY_XOME_API_KEY        (Xome Mortgage Team account)
 *   - `culbertson`  → process.env.MONDAY_CULBERTSON_API_KEY  (C&G account — legacy)
 *
 * Consumers call `getMondayData(widgetKey)` and receive:
 *   - on success:  `{ data: <transformed>, error: null }`
 *   - on missing key or any fetch error: `{ data: null, error: <message> }`
 *
 * Widgets treat `data: null` as the ComingSoon state and never crash server
 * components.
 *
 * All board/column/group/status mappings are pulled from the inventory
 * generated by `docs/xome-monday-inventory.json` during Phase 1 discovery.
 * Re-run `/tmp/xome-build-inventory.py` to regenerate.
 */

// ─── Types ──────────────────────────────────────────────────────────────

export type Tenant = 'xome' | 'culbertson'

export type WidgetKey =
  | 'xome.loan_pipeline'
  | 'xome.loan_officer_roster'
  | 'xome.loan_volume_kpis'
  | 'xome.compliance'
  | 'xome.warehouse_reconciliation'
  | 'xome.power'
  | 'xome.recent_closed_loans'
  | 'culbertson.loan_pipeline'            // legacy — not yet wired
  | 'culbertson.sales_volume_ytd'         // C&C Monday — Sales Volume YTD/MTD
  | 'culbertson.gci_ytd'                  // Gross commission income
  | 'culbertson.closed_transactions'      // Closed transaction count by period
  | 'culbertson.avg_commission_pct'       // Average commission %
  | 'culbertson.top_producers'            // Agent leaderboard by closed volume
  | 'culbertson.pipeline_value'           // Total $ in active deals
  | 'culbertson.revenue_by_source'        // Self-gen vs team-gen vs referral
  | 'culbertson.monthly_revenue'          // 12-month trend

export interface BoardMapping {
  tenant: Tenant
  widgetKey: WidgetKey
  boardId: string
  columns: Record<string, string>  // friendly -> monday column id
  groupMap?: Record<string, string>
  statusMap?: Record<string, string>
  transform?: (items: MondayItem[], mapping: BoardMapping) => unknown
}

export interface MondayItem {
  id: string
  name: string
  group?: { id: string; title: string }
  column_values: Array<{ id: string; type: string; text: string | null; value: string | null }>
}

export interface MondayResult<T = unknown> {
  data: T | null
  error: string | null
  cached?: boolean
}

// ─── Tenant → env var ────────────────────────────────────────────────────

const ENV_KEY_BY_TENANT: Record<Tenant, string> = {
  xome: 'MONDAY_XOME_API_KEY',
  culbertson: 'MONDAY_CULBERTSON_API_KEY',
}

function apiKeyForTenant(tenant: Tenant): string | null {
  const envVar = ENV_KEY_BY_TENANT[tenant]
  const v = process.env[envVar]
  return v && v.trim() ? v.trim() : null
}

// ─── In-memory cache (60s TTL) ──────────────────────────────────────────

interface CacheEntry {
  data: unknown
  expiresAt: number
}

const CACHE = new Map<string, CacheEntry>()
const CACHE_TTL_MS = 60_000

function cacheGet(key: string): unknown | null {
  const e = CACHE.get(key)
  if (!e) return null
  if (Date.now() > e.expiresAt) {
    CACHE.delete(key)
    return null
  }
  return e.data
}

function cacheSet(key: string, data: unknown): void {
  CACHE.set(key, { data, expiresAt: Date.now() + CACHE_TTL_MS })
}

// ─── GraphQL fetch ──────────────────────────────────────────────────────

export async function mondayFetch<T = unknown>(
  tenant: Tenant,
  query: string,
  variables: Record<string, unknown> = {}
): Promise<MondayResult<T>> {
  const apiKey = apiKeyForTenant(tenant)
  if (!apiKey) {
    return { data: null, error: `${ENV_KEY_BY_TENANT[tenant]} not configured` }
  }

  try {
    const res = await fetch('https://api.monday.com/v2', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: apiKey,
        'API-Version': '2024-01',
      },
      body: JSON.stringify({ query, variables }),
      cache: 'no-store',
    })

    if (res.status === 401) {
      return { data: null, error: '401 Unauthorized — bad or expired Monday token' }
    }
    if (res.status === 429) {
      return { data: null, error: '429 Rate limited by Monday API — try again in 60s' }
    }
    if (!res.ok) {
      return { data: null, error: `Monday API HTTP ${res.status}` }
    }

    const json = (await res.json()) as { data?: T; errors?: unknown[] }
    if (json.errors?.length) {
      return { data: null, error: `Monday API errors: ${JSON.stringify(json.errors)}` }
    }
    return { data: (json.data as T) ?? null, error: null }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    return { data: null, error: msg }
  }
}

// ─── Board mappings (from docs/xome-monday-inventory.json) ──────────────

const XOME_LOAN_PIPELINE_BOARD = '5842083369'

export const BOARD_MAPPINGS: BoardMapping[] = [
  // Loan Pipeline — primary production board (928 items, 7 groups)
  {
    tenant: 'xome',
    widgetKey: 'xome.loan_pipeline',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      last_name: 'name',
      first_name: 'text_1',
      lo: 'people',
      loa: 'people0',
      processor: 'people_2',
      stage: 'status',
      lender: 'label__1',
      lead_source: 'status_18',
      loan_purpose: 'dup__of_loan_purpose',
      loan_type: 'status_14',
      property_state: 'status106',
      property_address: 'location',
      estimated_value: 'numbers_1',
      est_loan_amount: 'numbers89',
      le_loan_amount: 'numbers4',
      appraised_value: 'numbers5',
      fico: 'numbers59',
      created_at: 'creation_log',
      updated_at: 'last_updated',
      pre_approved: 'date_1',
      coe: 'date_9',
      ctc: 'date6',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
    groupMap: {
      topics: 'Leads',
      new_group23653: 'Pre-Approved',
      new_group41491: 'In Process',
      group_mks3286t: 'New Group',
      new_group62657: 'Funded',
      new_group13782: 'Nurture',
      new_group9764: 'Dead/DNC',
    },
    statusMap: {
      '0': 'Registered',
      '1': 'Funded',
      '2': 'Incoming Registration',
      '3': 'Incoming Lead',
      '4': 'Contact Attempted Lead',
      '6': 'Contacted Lead',
      '9': 'CTC',
      '10': 'Appraisal Completed',
      '12': 'Loan Approved',
      '13': 'Loan Submitted',
      '18': 'Pre-Approved',
      '19': 'Appraisal Ordered',
      '105': 'Nurture',
      '106': 'Dead/Do Not Contact',
    },
  },

  // Loan Officer Roster — derived from the same Loan Pipeline board
  {
    tenant: 'xome',
    widgetKey: 'xome.loan_officer_roster',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      lo: 'people',
      stage: 'status',
      est_loan_amount: 'numbers89',
      le_loan_amount: 'numbers4',
      coe: 'date_9',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
  },

  // Loan Volume KPIs — derived from same board
  {
    tenant: 'xome',
    widgetKey: 'xome.loan_volume_kpis',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      stage: 'status',
      est_loan_amount: 'numbers89',
      le_loan_amount: 'numbers4',
      created_at: 'creation_log',
      coe: 'date_9',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
  },

  // Recent closed loans — same board, filtered to funded
  {
    tenant: 'xome',
    widgetKey: 'xome.recent_closed_loans',
    boardId: XOME_LOAN_PIPELINE_BOARD,
    columns: {
      last_name: 'name',
      first_name: 'text_1',
      stage: 'status',
      lo: 'people',
      le_loan_amount: 'numbers4',
      est_loan_amount: 'numbers89',
      property_state: 'status106',
      loan_type: 'status_14',
      loan_purpose: 'dup__of_loan_purpose',
      coe: 'date_9',
      wire_disbursement: 'dup__of_close_of_escrow',
    },
  },

  // Compliance Tracker — 0 items at discovery, column schema preserved
  {
    tenant: 'xome',
    widgetKey: 'xome.compliance',
    boardId: '18140546461',
    columns: {
      invoice_status: 'status4__1',
      processor_compliance: 'status_16',
      date_received: 'date4',
      cleared: 'status0',
      loan_amount_mirror: 'mirror',
      lo_mirror: 'mirror5',
    },
    groupMap: {
      new_group85895: 'Pending Compliance',
      new_group: 'Compliance Completed',
    },
  },

  // Warehouse Reconciliation — 0 items at discovery
  {
    tenant: 'xome',
    widgetKey: 'xome.warehouse_reconciliation',
    boardId: '18140546824',
    columns: {
      loan_amount_mirror: 'mirror3',
      warehouse_mirror: 'mirror4',
      lo_mirror: 'mirror0',
      funded_date_mirror: 'mirror6',
      total_wire: 'numbers980',
      to_be_funded: 'formula1',
      haircut: 'formula6',
      amount_due_investor: 'numbers96',
    },
    groupMap: {
      topics: 'Not Reconciled Yet',
      group_title: 'Reconciled',
    },
  },

  // Xome Power — solar board, small (3 items at discovery)
  {
    tenant: 'xome',
    widgetKey: 'xome.power',
    boardId: '6386432034',
    columns: {
      name: 'name',
      stage: 'status0',
      contacted: 'status9',
      street_address: 'text',
      city: 'text_1',
      financier: 'status68',
      installer: 'status72',
      date: 'date4',
    },
    groupMap: {
      topics: 'Incoming Leads',
      new_group52585: 'Proposal',
      new_group22586: 'Project',
      new_group22822: 'Completed',
      new_group: 'Nurture',
      new_group45402: 'Dead',
    },
  },

  // ─── Culbertson & Culbertson (C&G) — pending MONDAY_CULBERTSON_API_KEY ───
  // TODO: Column IDs below are placeholders. Fill after the C&C Monday
  // discovery scan runs against the real workspace (the scan is blocked
  // on the key landing in Vercel env).
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.sales_volume_ytd',
    boardId: 'TODO',
    columns: {
      // TODO: real column ids — sale price, close date, status, agent
      sale_price: 'TODO_numbers',
      close_date: 'TODO_date',
      status: 'TODO_status',
      agent: 'TODO_people',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.gci_ytd',
    boardId: 'TODO',
    columns: {
      gci: 'TODO_numbers',
      commission_pct: 'TODO_numbers',
      close_date: 'TODO_date',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.closed_transactions',
    boardId: 'TODO',
    columns: {
      status: 'TODO_status',
      close_date: 'TODO_date',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.avg_commission_pct',
    boardId: 'TODO',
    columns: {
      commission_pct: 'TODO_numbers',
      close_date: 'TODO_date',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.top_producers',
    boardId: 'TODO',
    columns: {
      agent: 'TODO_people',
      sale_price: 'TODO_numbers',
      gci: 'TODO_numbers',
      close_date: 'TODO_date',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.pipeline_value',
    boardId: 'TODO',
    columns: {
      deal_value: 'TODO_numbers',
      stage: 'TODO_status',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.revenue_by_source',
    boardId: 'TODO',
    columns: {
      source: 'TODO_status', // self-gen / team-gen / referral
      gci: 'TODO_numbers',
      close_date: 'TODO_date',
    },
  },
  {
    tenant: 'culbertson',
    widgetKey: 'culbertson.monthly_revenue',
    boardId: 'TODO',
    columns: {
      gci: 'TODO_numbers',
      close_date: 'TODO_date',
    },
  },
]

const MAPPING_BY_KEY: Record<string, BoardMapping> = Object.fromEntries(
  BOARD_MAPPINGS.map(m => [m.widgetKey, m])
)

// ─── Redaction helpers (for borrower display) ──────────────────────────

export function redactName(lastName: string | null, firstName?: string | null): string {
  const last = (lastName || '').trim()
  const first = (firstName || '').trim()
  if (first && last) return `${first[0]?.toUpperCase() ?? ''}. ${last}`
  if (last) return last
  if (first) return `${first[0]?.toUpperCase() ?? ''}.`
  return '—'
}

function parseNum(text: string | null | undefined): number {
  if (!text) return 0
  const n = Number(String(text).replace(/[^0-9.-]/g, ''))
  return Number.isFinite(n) ? n : 0
}

function cvText(item: MondayItem, id: string | undefined): string {
  if (!id) return ''
  const cv = item.column_values.find(c => c.id === id)
  return cv?.text ?? ''
}

// ─── Board fetchers ─────────────────────────────────────────────────────

/**
 * Paginate through all items on a board using cursor-based items_page.
 * Returns a flat array of items with the specified column_values.
 */
async function fetchBoardItems(
  tenant: Tenant,
  boardId: string,
  columnIds: string[],
  pageSize = 200
): Promise<MondayResult<MondayItem[]>> {
  const firstQuery = `
    query ($boardId: ID!, $columnIds: [String!], $limit: Int!) {
      boards(ids: [$boardId]) {
        items_page(limit: $limit) {
          cursor
          items {
            id
            name
            group { id title }
            column_values(ids: $columnIds) { id type text value }
          }
        }
      }
    }
  `
  const nextQuery = `
    query ($cursor: String!, $columnIds: [String!], $limit: Int!) {
      next_items_page(cursor: $cursor, limit: $limit) {
        cursor
        items {
          id
          name
          group { id title }
          column_values(ids: $columnIds) { id type text value }
        }
      }
    }
  `

  const r = await mondayFetch<{
    boards: Array<{ items_page: { cursor: string | null; items: MondayItem[] } }>
  }>(tenant, firstQuery, { boardId, columnIds, limit: pageSize })

  if (r.error || !r.data) return { data: null, error: r.error ?? 'No data' }

  const collected: MondayItem[] = []
  let cursor = r.data.boards?.[0]?.items_page?.cursor ?? null
  collected.push(...(r.data.boards?.[0]?.items_page?.items ?? []))

  // Safety cap to avoid infinite loops (board has 928 items; cap at ~5k)
  let hops = 0
  while (cursor && hops < 25) {
    hops++
    const n = await mondayFetch<{
      next_items_page: { cursor: string | null; items: MondayItem[] }
    }>(tenant, nextQuery, { cursor, columnIds, limit: pageSize })
    if (n.error || !n.data) break
    collected.push(...(n.data.next_items_page?.items ?? []))
    cursor = n.data.next_items_page?.cursor ?? null
  }

  return { data: collected, error: null }
}

// ─── Widget transforms ──────────────────────────────────────────────────

interface LoanPipelineStage {
  group_id: string
  group_name: string
  count: number
  total_amount: number
}

interface LoanPipelineView {
  board_id: string
  total_items: number
  total_active_amount: number
  stages: LoanPipelineStage[]
  generated_at: string
}

function transformLoanPipeline(items: MondayItem[], m: BoardMapping): LoanPipelineView {
  const groupMap = m.groupMap ?? {}
  const stages: Record<string, LoanPipelineStage> = {}

  // Seed every group so empty stages still render
  for (const [gid, gname] of Object.entries(groupMap)) {
    stages[gid] = { group_id: gid, group_name: gname, count: 0, total_amount: 0 }
  }

  for (const it of items) {
    const gid = it.group?.id ?? 'unknown'
    const gname = groupMap[gid] ?? it.group?.title ?? 'Other'
    if (!stages[gid]) stages[gid] = { group_id: gid, group_name: gname, count: 0, total_amount: 0 }
    stages[gid].count++

    // Prefer LE loan amount → estimated loan amount → estimated value
    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount)) ||
      parseNum(cvText(it, m.columns.estimated_value))
    stages[gid].total_amount += amount
  }

  // Keep the groups in the same declaration order as groupMap; unknowns last
  const ordered: LoanPipelineStage[] = []
  const seen = new Set<string>()
  for (const gid of Object.keys(groupMap)) {
    if (stages[gid]) {
      ordered.push(stages[gid])
      seen.add(gid)
    }
  }
  for (const [gid, s] of Object.entries(stages)) {
    if (!seen.has(gid)) ordered.push(s)
  }

  const active_groups = new Set(['topics', 'new_group23653', 'new_group41491', 'group_mks3286t'])
  const total_active_amount = ordered
    .filter(s => active_groups.has(s.group_id))
    .reduce((sum, s) => sum + s.total_amount, 0)

  return {
    board_id: m.boardId,
    total_items: items.length,
    total_active_amount,
    stages: ordered,
    generated_at: new Date().toISOString(),
  }
}

interface LoanOfficerRow {
  name: string
  loan_count: number
  active_count: number
  funded_count: number
  volume_mtd: number
  volume_ytd: number
}

function transformLoanOfficers(items: MondayItem[], m: BoardMapping): LoanOfficerRow[] {
  const now = new Date()
  const mtdStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const ytdStart = new Date(now.getFullYear(), 0, 1)

  const officers = new Map<string, LoanOfficerRow>()

  for (const it of items) {
    const loText = cvText(it, m.columns.lo)
    const loName = loText?.trim() || 'Unassigned'
    if (!officers.has(loName)) {
      officers.set(loName, {
        name: loName,
        loan_count: 0,
        active_count: 0,
        funded_count: 0,
        volume_mtd: 0,
        volume_ytd: 0,
      })
    }
    const rec = officers.get(loName)!
    rec.loan_count++

    const stage = cvText(it, m.columns.stage) || ''
    const groupId = it.group?.id ?? ''
    const isFunded = stage === 'Funded' || groupId === 'new_group62657'
    const isDead = groupId === 'new_group9764' || groupId === 'new_group13782'

    if (isFunded) rec.funded_count++
    else if (!isDead) rec.active_count++

    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount))
    const closeStr = cvText(it, m.columns.coe) || cvText(it, m.columns.wire_disbursement)

    if (isFunded && amount > 0 && closeStr) {
      const closeDate = new Date(closeStr)
      if (!isNaN(closeDate.getTime())) {
        if (closeDate >= ytdStart) rec.volume_ytd += amount
        if (closeDate >= mtdStart) rec.volume_mtd += amount
      }
    }
  }

  return Array.from(officers.values())
    .filter(r => r.name !== 'Unassigned')
    .sort((a, b) => b.volume_ytd - a.volume_ytd || b.funded_count - a.funded_count)
}

interface LoanVolumeKPIs {
  volume_mtd: number
  volume_ytd: number
  loans_funded_mtd: number
  loans_funded_ytd: number
  avg_loan_size: number
  pipeline_value: number
  pipeline_count: number
  avg_days_to_close: number | null
  pull_through_rate: number | null
}

function transformLoanVolumeKPIs(items: MondayItem[], m: BoardMapping): LoanVolumeKPIs {
  const now = new Date()
  const mtdStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const ytdStart = new Date(now.getFullYear(), 0, 1)

  let volume_mtd = 0
  let volume_ytd = 0
  let loans_funded_mtd = 0
  let loans_funded_ytd = 0
  let funded_sum = 0
  let funded_count = 0
  let pipeline_value = 0
  let pipeline_count = 0
  const closeDays: number[] = []

  const active_groups = new Set(['topics', 'new_group23653', 'new_group41491', 'group_mks3286t'])

  for (const it of items) {
    const stage = cvText(it, m.columns.stage) || ''
    const groupId = it.group?.id ?? ''
    const isFunded = stage === 'Funded' || groupId === 'new_group62657'

    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount))

    if (isFunded && amount > 0) {
      const closeStr = cvText(it, m.columns.coe) || cvText(it, m.columns.wire_disbursement)
      const closeDate = closeStr ? new Date(closeStr) : null
      const createdStr = cvText(it, m.columns.created_at)
      const createdDate = createdStr ? new Date(createdStr) : null

      funded_sum += amount
      funded_count++

      if (closeDate && !isNaN(closeDate.getTime())) {
        if (closeDate >= ytdStart) {
          volume_ytd += amount
          loans_funded_ytd++
        }
        if (closeDate >= mtdStart) {
          volume_mtd += amount
          loans_funded_mtd++
        }
        if (createdDate && !isNaN(createdDate.getTime())) {
          const days = Math.round((closeDate.getTime() - createdDate.getTime()) / 86_400_000)
          if (days > 0 && days < 365) closeDays.push(days)
        }
      }
    }

    if (active_groups.has(groupId)) {
      pipeline_count++
      pipeline_value += amount
    }
  }

  const avg_days_to_close =
    closeDays.length > 0 ? Math.round(closeDays.reduce((a, b) => a + b, 0) / closeDays.length) : null
  const avg_loan_size = funded_count > 0 ? funded_sum / funded_count : 0
  const totalCountable = items.filter(it => {
    const gid = it.group?.id ?? ''
    return gid !== 'new_group9764' && gid !== 'new_group13782'
  }).length
  const pull_through_rate = totalCountable > 0 ? funded_count / totalCountable : null

  return {
    volume_mtd,
    volume_ytd,
    loans_funded_mtd,
    loans_funded_ytd,
    avg_loan_size,
    pipeline_value,
    pipeline_count,
    avg_days_to_close,
    pull_through_rate,
  }
}

interface ClosedLoanRow {
  id: string
  borrower: string
  amount: number
  lo: string
  state: string
  loan_type: string
  loan_purpose: string
  close_date: string | null
}

function transformRecentClosed(items: MondayItem[], m: BoardMapping, limit = 10): ClosedLoanRow[] {
  const rows: ClosedLoanRow[] = []
  for (const it of items) {
    const stage = cvText(it, m.columns.stage) || ''
    const groupId = it.group?.id ?? ''
    const isFunded = stage === 'Funded' || groupId === 'new_group62657'
    if (!isFunded) continue

    const amount =
      parseNum(cvText(it, m.columns.le_loan_amount)) ||
      parseNum(cvText(it, m.columns.est_loan_amount))
    const closeStr = cvText(it, m.columns.coe) || cvText(it, m.columns.wire_disbursement) || null

    rows.push({
      id: it.id,
      borrower: redactName(it.name, cvText(it, m.columns.first_name)),
      amount,
      lo: cvText(it, m.columns.lo) || '—',
      state: cvText(it, m.columns.property_state) || '—',
      loan_type: cvText(it, m.columns.loan_type) || '—',
      loan_purpose: cvText(it, m.columns.loan_purpose) || '—',
      close_date: closeStr,
    })
  }
  rows.sort((a, b) => {
    const ad = a.close_date ? new Date(a.close_date).getTime() : 0
    const bd = b.close_date ? new Date(b.close_date).getTime() : 0
    return bd - ad
  })
  return rows.slice(0, limit)
}

interface ComplianceView {
  board_id: string
  total_items: number
  pending_count: number
  completed_count: number
  overdue_count: number
  items: Array<{
    id: string
    name: string
    group: string
    date_received: string | null
    processor_compliance: string
    invoice_status: string
    cleared: string
    overdue: boolean
  }>
}

function transformCompliance(items: MondayItem[], m: BoardMapping): ComplianceView {
  const now = Date.now()
  const overdueWindowMs = 14 * 86_400_000

  const rows = items.map(it => {
    const dateStr = cvText(it, m.columns.date_received)
    const date = dateStr ? new Date(dateStr) : null
    const overdue =
      !!date && !isNaN(date.getTime()) && now - date.getTime() > overdueWindowMs &&
      !cvText(it, m.columns.cleared).toLowerCase().includes('yes')
    const gid = it.group?.id ?? ''
    const gname = m.groupMap?.[gid] ?? it.group?.title ?? 'Other'
    return {
      id: it.id,
      name: it.name,
      group: gname,
      date_received: dateStr || null,
      processor_compliance: cvText(it, m.columns.processor_compliance),
      invoice_status: cvText(it, m.columns.invoice_status),
      cleared: cvText(it, m.columns.cleared),
      overdue,
    }
  })

  const pending_count = rows.filter(r => r.group === 'Pending Compliance').length
  const completed_count = rows.filter(r => r.group === 'Compliance Completed').length
  const overdue_count = rows.filter(r => r.overdue).length

  return {
    board_id: m.boardId,
    total_items: items.length,
    pending_count,
    completed_count,
    overdue_count,
    items: rows.slice(0, 20),
  }
}

interface WarehouseView {
  board_id: string
  open_count: number
  reconciled_count: number
  total_pending_value: number
  total_haircut: number
  oldest_open_days: number | null
}

function transformWarehouse(items: MondayItem[], m: BoardMapping): WarehouseView {
  let open_count = 0
  let reconciled_count = 0
  let total_pending_value = 0
  let total_haircut = 0
  let oldest_ms: number | null = null
  const now = Date.now()

  for (const it of items) {
    const gid = it.group?.id ?? ''
    const amount = parseNum(cvText(it, m.columns.total_wire)) || parseNum(cvText(it, m.columns.loan_amount_mirror))
    const haircut = parseNum(cvText(it, m.columns.haircut))

    if (gid === 'topics') {
      open_count++
      total_pending_value += amount
      total_haircut += haircut
      const fundedStr = cvText(it, m.columns.funded_date_mirror)
      if (fundedStr) {
        const d = new Date(fundedStr).getTime()
        if (!isNaN(d) && (oldest_ms === null || d < oldest_ms)) oldest_ms = d
      }
    } else if (gid === 'group_title') {
      reconciled_count++
    }
  }

  const oldest_open_days =
    oldest_ms !== null ? Math.floor((now - oldest_ms) / 86_400_000) : null

  return {
    board_id: m.boardId,
    open_count,
    reconciled_count,
    total_pending_value,
    total_haircut,
    oldest_open_days,
  }
}

interface XomePowerView {
  board_id: string
  total_items: number
  stages: Array<{ group_id: string; group_name: string; count: number }>
  items: Array<{ id: string; name: string; group: string; stage: string; contacted: string; city: string }>
}

function transformXomePower(items: MondayItem[], m: BoardMapping): XomePowerView {
  const groupMap = m.groupMap ?? {}
  const stages: Record<string, { group_id: string; group_name: string; count: number }> = {}
  for (const [gid, gname] of Object.entries(groupMap)) {
    stages[gid] = { group_id: gid, group_name: gname, count: 0 }
  }
  for (const it of items) {
    const gid = it.group?.id ?? 'unknown'
    if (!stages[gid]) {
      stages[gid] = { group_id: gid, group_name: it.group?.title ?? 'Other', count: 0 }
    }
    stages[gid].count++
  }
  return {
    board_id: m.boardId,
    total_items: items.length,
    stages: Object.values(stages),
    items: items.slice(0, 10).map(it => {
      const lastName = (it.name || '').split(' ')[0] || '—'
      return {
        id: it.id,
        name: `${lastName[0]?.toUpperCase() || ''}. ${it.name?.split(' ').slice(1).join(' ') || ''}`.trim() || it.name,
        group: m.groupMap?.[it.group?.id ?? ''] ?? it.group?.title ?? 'Other',
        stage: cvText(it, m.columns.stage),
        contacted: cvText(it, m.columns.contacted),
        city: cvText(it, m.columns.city),
      }
    }),
  }
}

// ─── Public API ─────────────────────────────────────────────────────────

export async function getMondayData(widgetKey: WidgetKey): Promise<MondayResult> {
  const mapping = MAPPING_BY_KEY[widgetKey]
  if (!mapping) {
    return { data: null, error: `Unknown widget key: ${widgetKey}` }
  }

  const cacheKey = `${mapping.tenant}:${widgetKey}`
  const cached = cacheGet(cacheKey)
  if (cached) {
    return { data: cached, error: null, cached: true }
  }

  // If no API key, short-circuit with explicit error
  if (!apiKeyForTenant(mapping.tenant)) {
    return { data: null, error: `${ENV_KEY_BY_TENANT[mapping.tenant]} not configured` }
  }

  // Collect column IDs we need + always include `name`, `group`
  const columnIds = Array.from(new Set(Object.values(mapping.columns))).filter(Boolean)
  const result = await fetchBoardItems(mapping.tenant, mapping.boardId, columnIds)
  if (result.error || !result.data) {
    return { data: null, error: result.error ?? 'No items returned' }
  }

  let transformed: unknown
  try {
    switch (widgetKey) {
      case 'xome.loan_pipeline':
        transformed = transformLoanPipeline(result.data, mapping)
        break
      case 'xome.loan_officer_roster':
        transformed = transformLoanOfficers(result.data, mapping)
        break
      case 'xome.loan_volume_kpis':
        transformed = transformLoanVolumeKPIs(result.data, mapping)
        break
      case 'xome.recent_closed_loans':
        transformed = transformRecentClosed(result.data, mapping)
        break
      case 'xome.compliance':
        transformed = transformCompliance(result.data, mapping)
        break
      case 'xome.warehouse_reconciliation':
        transformed = transformWarehouse(result.data, mapping)
        break
      case 'xome.power':
        transformed = transformXomePower(result.data, mapping)
        break
      default:
        transformed = result.data
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    return { data: null, error: `Transform failed: ${msg}` }
  }

  cacheSet(cacheKey, transformed)
  return { data: transformed, error: null }
}

// Helpful re-exports for widget code
export type {
  LoanPipelineView,
  LoanPipelineStage,
  LoanOfficerRow,
  LoanVolumeKPIs,
  ClosedLoanRow,
  ComplianceView,
  WarehouseView,
  XomePowerView,
}
